apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: ai-autoscaler

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: manojs0723/project6-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 4000

          envFrom:
            - configMapRef:
                name: backend-config

            - secretRef:
                name: backend-secret