apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: ai-autoscaler

type: Opaque

stringData:
  MONGODB_URI: mongodb://admin:admin123@mongodb:27017/autoscaler?authSource=adminapiVersion: v1
kind: Secret

metadata:
  name: mongodb-secret
  namespace: ai-autoscaler

type: Opaque

stringData:
  MONGO_INITDB_ROOT_USERNAME: "<MONGO_USERNAME>"
  MONGO_INITDB_ROOT_PASSWORD: "<MONGO_PASSWORD>"